RUN_SCHEMA_MANIFEST ?= 1
RUN_DEPS_CHECK ?= 0
RUN_BATCH ?= 0

.PHONY: preflight
preflight:
	@echo "Running preflight (RUN_SCHEMA_MANIFEST=$(RUN_SCHEMA_MANIFEST), RUN_DEPS_CHECK=$(RUN_DEPS_CHECK), RUN_BATCH=$(RUN_BATCH))"
	@RUN_SCHEMA_MANIFEST=$(RUN_SCHEMA_MANIFEST) RUN_DEPS_CHECK=$(RUN_DEPS_CHECK) RUN_BATCH=$(RUN_BATCH) bash scripts/verify/preflight.sh
